### PR TITLE
Add support for `FileFormat::from_extension` which returns a Vec of formats for the extension

### PR DESCRIPTION
**Pull request by veeshi**

### CODE REVIEW

**Comment by mmalecot** [comment]
Thanks for your PR!
I'll have a look ASAP.

I think the `rust-1_70` feature is not necessary and we can move on to 1.70 as MSRV.

**Comment by mmalecot** [comment]
I like the idea, but the crate isn't quite ready for that: each file format has a single preferred extension.
For example, for `JPEG` it's `.jpg`, so `FileFormat::from_extension("jpeg")` will return an empty vec.

The only solution for having a relevant API is to have additional extensions on the file formats. I'll think about that.

Thanks

**Comment by veeshi** [comment]
It will need a separate list of additional extensions I think. shared-mime-info solves it with the globs2 list which has the weight, mime type and extension together.

**Comment by veeshi** [comment]
I've added some common extensions for each file format and changed the macro and API

**Comment by mmalecot** [comment]
Sorry for the delay in replying as I've been busy with other things lately.

# For `FileFormat::from_extension`

Although the API idea is good, the PR is incomplete and requires adding the possible extensions of all existing file formats, which represents a substantial task.

# For `FileFormat::from_media_type`

If you still think this API is interesting, why not implement it.

# Conclusion

In any case, you'll have to rebase your branch because the `file-format` code has evolved a bit. If you're motivated, you can make a first PR for `from_media_type`, and if you're very motivated, why not start work on `from_extension`.

Thanks in any case for the work, and don't hesitate to suggest other things to the `file-format` crate!

**Pull request closed without merging**
